create database hotel_booking;
use hotel_booking;

ALTER TABLE `hotel reservation dataset`
CHANGE COLUMN `ï»¿Booking_ID` booking_id VARCHAR(20);

-- 1. View all records
SELECT * FROM `hotel reservation dataset`;

-- 2. Show only booking ID, adults, children
SELECT booking_id, no_of_adults, no_of_children
FROM `hotel reservation dataset`;

-- 3. Find total number of bookings
SELECT COUNT(*) AS total_bookings
FROM `hotel reservation dataset`;

-- 4. Find average room price
SELECT ROUND(AVG(avg_price_per_room), 2) AS average_room_price
FROM `hotel reservation dataset`;

-- 5. Show bookings with more than 2 adults
SELECT *
FROM `hotel reservation dataset`
WHERE no_of_adults > 2;

-- 6. Total bookings by market segment
SELECT market_segment_type, COUNT(*) AS bookings
FROM `hotel reservation dataset`
GROUP BY market_segment_type
ORDER BY bookings DESC;

-- 7. Revenue generated by each room type
SELECT room_type_reserved,
       ROUND(SUM(avg_price_per_room), 2) AS total_revenue
FROM `hotel reservation dataset`
GROUP BY room_type_reserved
ORDER BY total_revenue DESC;

-- 8. Average lead time by booking status
SELECT booking_status,
       ROUND(AVG(lead_time), 2) AS avg_lead_time
FROM `hotel reservation dataset`
GROUP BY booking_status;

-- 9. Top 5 most expensive bookings
SELECT booking_id, no_of_adults, no_of_children, avg_price_per_room
FROM `hotel reservation dataset`
ORDER BY avg_price_per_room DESC
LIMIT 5;

-- 10. Average number of nights (weekend + weekday) per room type
SELECT room_type_reserved,
    ROUND(AVG(no_of_weekend_nights + no_of_week_nights), 2) AS avg_total_nights
FROM `hotel reservation dataset`
GROUP BY room_type_reserved
ORDER BY avg_total_nights DESC;

-- 11. Most popular meal plan for bookings with >2 persons (adults+children)
SELECT type_of_meal_plan,
    COUNT(*) AS bookings
FROM `hotel reservation dataset`
WHERE (no_of_adults + no_of_children) > 2
GROUP BY type_of_meal_plan
ORDER BY bookings DESC;